
POST http://localhost:3001/api/persons/
Content-type: application/json

{
    "id": 555,
    "name": "aab aac aad",
    "number": "243 2432 4344"
}

//POST https://puhluettelo.onrender.com/api/persons
//Content-type: application/json

//{
//    "id": 5,
//    "name": "3.13testi",
//    "number": "33343443"
//}

